FROM anapsix/alpine-java
COPY target/trend-puller-1.0-SNAPSHOT-jar-with-dependencies.jar /home/trend-puller-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java","-jar","/home/trend-puller-1.0-SNAPSHOT-jar-with-dependencies.jar"]